[package]
name = "xdsim-cbinds"
version = "0.1.0"
edition = "2024"

[dependencies]

[features]
default = ["v0-all", "impl"]
# default = []
v0-all = [ "v0-gate", "v0-data", "v0-conn" ]
v0-gate = []
v0-conn = []
v0-data = []

impl = []
